### ISSUE TITLE
Function of the node hotspot

### ISSUE THREAD

**Issue by Paul-Reed** [mblackstock/node-red-contrib-data-view#2]
A very welcome node Mike, thank you!
Just an observation... I wondered if the hotspot would be of more value if it actually hid the chart from view, instead of just stopping it.

**Comment by mblackstock** [comment]
Good idea, maybe I will make that an option like hide on deactivate or
something.  Thanks!

**Comment by ghayne** [comment]
I agree with Paul-Reed on this, in fact it was the behaviour I expected. It would be especially useful in complex flows to avoid clutter when using the node purely for debugging.

**Comment by mblackstock** [comment]
added hide on deactivate, true by default.  on develop branch.
