### ISSUE TITLE
use property as default name

### ISSUE THREAD

**Issue by mblackstock** [mblackstock/node-red-contrib-data-view#8]

**Comment by Paul-Reed** [comment]
I can see why you have made this change... but isn't it moving away from the node-RED model which users are familiar with?
![error](https://user-images.githubusercontent.com/973580/103469283-c60bf580-4d5a-11eb-8781-a1a29198706e.JPG)
A consideration could be adding a user defined title to the chart itself.

**Comment by mblackstock** [comment]
I modelled it after the debug node.  This way you know immediately what property you are graphing, which is important since you can now change it.  I believe this was a suggestion by @dceejay.

A user defined chart title might be cool, but you can already rename the node, which overrides this default name.  I'm not sure we'd need another name?
